### testfile to convert Docker-file to K8s

version: '3'

services:
  redis-leader:
    container_name: redis-leader
    image: redis
    ports:
      - "6379:6379"

  redis-replica:
    container_name: redis-replica
    image: redis
    ports:
      - "6380:6379" # 포트 충돌 방지
    command: redis-server --replicaof redis-leader 6379 --dir /tmp

  web:
    container_name: web
    image: quay.io/kompose/web
    ports:
      - "8080:8080"
    environment:
      - GET_HOSTS_FROM=dns
