apiVersion: v1
kind: Service
metadata:
  name: library-portal-nodeport
  labels:
    app: library-portal
    service: library-portal
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30081
    name: http
  selector:
    app: library-portal
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
  labels:
    app: user-service
    service: user-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30082
    name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: search-service-nodeport
  labels:
    app: search-service
    service: search-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30083
    name: http
  selector:
    app: search-service
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service-nodeport
  labels:
    app: analytics-service
    service: analytics-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30084
    name: http
  selector:
    app: analytics-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
  labels:
    app: order-service
    service: order-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30085
    name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-nodeport
  labels:
    app: inventory-service
    service: inventory-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30086
    name: http
  selector:
    app: inventory-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-nodeport
  labels:
    app: payment-service
    service: payment-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30087
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-nodeport
  labels:
    app: notification-service
    service: notification-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30088
    name: http
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service-nodeport
  labels:
    app: recommendation-service
    service: recommendation-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30089
    name: http
  selector:
    app: recommendation-service
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-nodeport
  labels:
    app: catalog-service
    service: catalog-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30090
    name: http
  selector:
    app: catalog-service
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-nodeport
  labels:
    app: shipping-service
    service: shipping-service
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30091
    name: http
  selector:
    app: shipping-service 